### ISSUE TITLE
Please request pull request

### ISSUE THREAD

**Issue by namanj2003** [TAbhay/Hactoberfest-2021#194]
Sir,
I have participated in Hactoberfest 2020 and only 3 days are remaining for it to end.
I therefore humbly request you to kindly accept my pull request as soo as possible or else i wont be able to complete the Hactoberfest task on time. So I request you to please accept the pull requests as soon as possible.

**Comment by Kishorsarswat** [comment]
> Sir,
> I have participated in Hactoberfest 2020 and only 3 days are remaining for it to end.
> I therefore humbly request you to kindly accept my pull request as soo as possible or else i wont be able to complete the Hactoberfest task on time. So I request you to please accept the pull requests as soon as possible.

hey Naman, you can pull request in my repositry if you want to add any code for Hactoberfest. I'll be happy to accept any code. have a look at https://github.com/Kishorsarswat/greedy-questions this repo. fork it, clone it make changes and pull request.

**Comment by TAbhay** [comment]
Done
