### ISSUE TITLE
For easy Merge

### ISSUE THREAD

**Issue by vijaygupta18** [TAbhay/Hactoberfest-2021#333]
For easy contribution create pr on this repo.

https://github.com/vijaygupta18/Hacktoberfest-2021

**Comment by nishantkumar1308** [comment]
I am working on Dyanamic programming.

**Comment by Padmanabh82** [comment]
please accept my pull request. ihave put my project in it

**Comment by Padmanabh82** [comment]
but i don't know how it is added as sub module.will it work

**Comment by Padmanabh82** [comment]
and what will happen after you accept it ??

**Comment by vijaygupta18** [comment]
> and what will happen after you accept it ??

visit the repo.. fork it and then after pushing your project create a PR

**Comment by Padmanabh82** [comment]
please accept my pull request :-  https://github.com/TAbhay/Hactoberfest-2021/pull/446

**Comment by HiruniPerera** [comment]
Hello would love to contribute to this.can i add my project to this?

**Comment by vijaygupta18** [comment]
> Hello would love to contribute to this.can i add my project to this?

yeah ofcourse
