### ISSUE TITLE
Need 2-3 Collaborators 

### ISSUE THREAD

**Issue by TAbhay** [TAbhay/Hactoberfest-2021#575]
# Tasks  🚀🚀🚀🚀

**Comment by nishantkumar1308** [comment]
@TAbhay I can help I have a basic knowledge on github and git.

**Comment by harshitsuthar77731** [comment]
@TAbhay i want to collobrate with @nishantkumar1308

**Comment by himanshukaushal123** [comment]
Please give it to me i have knowledge about this

**Comment by himanshukaushal123** [comment]
@TAbhay i want to collaborate with @nishantkumar1308

**Comment by TAbhay** [comment]
@nishantkumar1308 @harshitsuthar77731 @himanshukaushal123 Okay ... accept invites

**Comment by nishantkumar1308** [comment]
can we start working on checking and merging  pr's?

**Comment by TAbhay** [comment]
@nishantkumar1308 @himanshukaushal123 @harshitsuthar77731 
Check and merge PR's 🚀

**Comment by TAbhay** [comment]
> I would like to contribute too

Added

**Comment by FahimFBA** [comment]
I would want to contribute in this regard @TAbhay.

**Comment by sohailalamoffic** [comment]
Can I contribute to it also ?? @TAbhay

**Comment by Anjaan-g** [comment]
> > I would like to contribute too
> 
> Added

Sorry, I couldn't accept the invitation due to some personal problems before, can you send it again? Thanks!

**Comment by sohailalamoffic** [comment]
Hi I would like to contribute also
 @TAbhay
