### ISSUE TITLE
Mergesort Algorithm

### ISSUE THREAD

**Issue by archanagandhi** [TAbhay/Hactoberfest-2021#585]
Implementation of Merge sort algorithm using Python.

Please assign this issue to me.

**Comment by harsh6975** [comment]
Merge sort is the divide and conqueror technique. I will explain the code and intuition behind the algorithm with proper comments in c++.
Please Assing me.
Thanks

**Comment by surajwakka** [comment]
Merge Sort algorithm using C++
Pls assign me this issue ...

**Comment by Saurabh65004** [comment]
Hey there please assign this issue to me, I will make a good code for merge sort Algorithm in JAVA.

**Comment by Richa-Bharti** [comment]
Implementation of Merge Sort algorithm using Java from a 4 star HackerRank Coder.
Please assign this issue to me

**Comment by TAbhay** [comment]
> Implementation of Merge sort algorithm using Python.
> 
> Please assign this issue to me.

Okay

**Comment by saransh37** [comment]
Merge Sort C++.
Plz assign this issue  to me.
